source = "/FVCOM_source"
surface_forcing = "/FVCOM_source/input/surface_forcing"
init_wqm = "/FVCOM_source/input/init_wqm"
pro_read = "/FVCOM_source/input/PRO_READ"
run = "/run"
output = "/run/ZQH_OUTPUT"
